name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.4

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Code quality checks
      run: |
        poetry run black --check .
        poetry run ruff check .

    - name: Test single function  
      run: poetry run pytest tests/test_cli.py::test_main_help -v

    - name: All tests (if single works)
      run: poetry run pytest -x -v
      if: success() 